'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SH_WS_Produccion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SH_WS_Produccion.SH_WSSoap")>  _
    Public Interface SH_WSSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Login", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Login(ByVal Nombre_Dispositivo As String, ByVal Usuario As String, ByVal Pwd As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Login", ReplyAction:="*")>  _
        Function LoginAsync(ByVal Nombre_Dispositivo As String, ByVal Usuario As String, ByVal Pwd As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_TemperaturaObjetivo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_TemperaturaObjetivo() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_TemperaturaObjetivo", ReplyAction:="*")>  _
        Function GET_TemperaturaObjetivoAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SET_TemperaturaObjetivo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SET_TemperaturaObjetivo(ByVal NuevaTemp As Double) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SET_TemperaturaObjetivo", ReplyAction:="*")>  _
        Function SET_TemperaturaObjetivoAsync(ByVal NuevaTemp As Double) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Calefaccion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_Calefaccion() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Calefaccion", ReplyAction:="*")>  _
        Function GET_CalefaccionAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Calefaccion_Encendida", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_Calefaccion_Encendida() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Calefaccion_Encendida", ReplyAction:="*")>  _
        Function GET_Calefaccion_EncendidaAsync() As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/NEW_Lectura", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function NEW_Lectura(ByVal NOMBRE_DISP As String, ByVal TEMPERATURA_ACTUAL As Double, ByVal HUMEDAD As Double) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/NEW_Lectura", ReplyAction:="*")>  _
        Function NEW_LecturaAsync(ByVal NOMBRE_DISP As String, ByVal TEMPERATURA_ACTUAL As Double, ByVal HUMEDAD As Double) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Lecturas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_Lecturas(ByVal Dispositivo As String, ByVal cantidad As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Lecturas", ReplyAction:="*")>  _
        Function GET_LecturasAsync(ByVal Dispositivo As String, ByVal cantidad As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Lecturas_Fecha", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_Lecturas_Fecha(ByVal NombreDispositivo As String, ByVal Fecha As Date) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Lecturas_Fecha", ReplyAction:="*")>  _
        Function GET_Lecturas_FechaAsync(ByVal NombreDispositivo As String, ByVal Fecha As Date) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Servidor_Fecha", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_Servidor_Fecha() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Servidor_Fecha", ReplyAction:="*")>  _
        Function GET_Servidor_FechaAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Dispositivos_Configuración", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_Dispositivos_Configuración(ByVal NombreDispositivo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_Dispositivos_Configuración", ReplyAction:="*")>  _
        Function GET_Dispositivos_ConfiguraciónAsync(ByVal NombreDispositivo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/NEW_Dispositivo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function NEW_Dispositivo(ByVal NOMBRE_DISP As String, ByVal IP As String, ByVal ROL As String, ByVal LOCALIZACION As String, ByVal MODELO As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/NEW_Dispositivo", ReplyAction:="*")>  _
        Function NEW_DispositivoAsync(ByVal NOMBRE_DISP As String, ByVal IP As String, ByVal ROL As String, ByVal LOCALIZACION As String, ByVal MODELO As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SH_WSSoapChannel
        Inherits SH_WS_Produccion.SH_WSSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SH_WSSoapClient
        Inherits System.ServiceModel.ClientBase(Of SH_WS_Produccion.SH_WSSoap)
        Implements SH_WS_Produccion.SH_WSSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Login(ByVal Nombre_Dispositivo As String, ByVal Usuario As String, ByVal Pwd As String) As Boolean Implements SH_WS_Produccion.SH_WSSoap.Login
            Return MyBase.Channel.Login(Nombre_Dispositivo, Usuario, Pwd)
        End Function
        
        Public Function LoginAsync(ByVal Nombre_Dispositivo As String, ByVal Usuario As String, ByVal Pwd As String) As System.Threading.Tasks.Task(Of Boolean) Implements SH_WS_Produccion.SH_WSSoap.LoginAsync
            Return MyBase.Channel.LoginAsync(Nombre_Dispositivo, Usuario, Pwd)
        End Function
        
        Public Function GET_TemperaturaObjetivo() As String Implements SH_WS_Produccion.SH_WSSoap.GET_TemperaturaObjetivo
            Return MyBase.Channel.GET_TemperaturaObjetivo
        End Function
        
        Public Function GET_TemperaturaObjetivoAsync() As System.Threading.Tasks.Task(Of String) Implements SH_WS_Produccion.SH_WSSoap.GET_TemperaturaObjetivoAsync
            Return MyBase.Channel.GET_TemperaturaObjetivoAsync
        End Function
        
        Public Function SET_TemperaturaObjetivo(ByVal NuevaTemp As Double) As String Implements SH_WS_Produccion.SH_WSSoap.SET_TemperaturaObjetivo
            Return MyBase.Channel.SET_TemperaturaObjetivo(NuevaTemp)
        End Function
        
        Public Function SET_TemperaturaObjetivoAsync(ByVal NuevaTemp As Double) As System.Threading.Tasks.Task(Of String) Implements SH_WS_Produccion.SH_WSSoap.SET_TemperaturaObjetivoAsync
            Return MyBase.Channel.SET_TemperaturaObjetivoAsync(NuevaTemp)
        End Function
        
        Public Function GET_Calefaccion() As String Implements SH_WS_Produccion.SH_WSSoap.GET_Calefaccion
            Return MyBase.Channel.GET_Calefaccion
        End Function
        
        Public Function GET_CalefaccionAsync() As System.Threading.Tasks.Task(Of String) Implements SH_WS_Produccion.SH_WSSoap.GET_CalefaccionAsync
            Return MyBase.Channel.GET_CalefaccionAsync
        End Function
        
        Public Function GET_Calefaccion_Encendida() As Boolean Implements SH_WS_Produccion.SH_WSSoap.GET_Calefaccion_Encendida
            Return MyBase.Channel.GET_Calefaccion_Encendida
        End Function
        
        Public Function GET_Calefaccion_EncendidaAsync() As System.Threading.Tasks.Task(Of Boolean) Implements SH_WS_Produccion.SH_WSSoap.GET_Calefaccion_EncendidaAsync
            Return MyBase.Channel.GET_Calefaccion_EncendidaAsync
        End Function
        
        Public Function NEW_Lectura(ByVal NOMBRE_DISP As String, ByVal TEMPERATURA_ACTUAL As Double, ByVal HUMEDAD As Double) As Boolean Implements SH_WS_Produccion.SH_WSSoap.NEW_Lectura
            Return MyBase.Channel.NEW_Lectura(NOMBRE_DISP, TEMPERATURA_ACTUAL, HUMEDAD)
        End Function
        
        Public Function NEW_LecturaAsync(ByVal NOMBRE_DISP As String, ByVal TEMPERATURA_ACTUAL As Double, ByVal HUMEDAD As Double) As System.Threading.Tasks.Task(Of Boolean) Implements SH_WS_Produccion.SH_WSSoap.NEW_LecturaAsync
            Return MyBase.Channel.NEW_LecturaAsync(NOMBRE_DISP, TEMPERATURA_ACTUAL, HUMEDAD)
        End Function
        
        Public Function GET_Lecturas(ByVal Dispositivo As String, ByVal cantidad As Integer) As String Implements SH_WS_Produccion.SH_WSSoap.GET_Lecturas
            Return MyBase.Channel.GET_Lecturas(Dispositivo, cantidad)
        End Function
        
        Public Function GET_LecturasAsync(ByVal Dispositivo As String, ByVal cantidad As Integer) As System.Threading.Tasks.Task(Of String) Implements SH_WS_Produccion.SH_WSSoap.GET_LecturasAsync
            Return MyBase.Channel.GET_LecturasAsync(Dispositivo, cantidad)
        End Function
        
        Public Function GET_Lecturas_Fecha(ByVal NombreDispositivo As String, ByVal Fecha As Date) As String Implements SH_WS_Produccion.SH_WSSoap.GET_Lecturas_Fecha
            Return MyBase.Channel.GET_Lecturas_Fecha(NombreDispositivo, Fecha)
        End Function
        
        Public Function GET_Lecturas_FechaAsync(ByVal NombreDispositivo As String, ByVal Fecha As Date) As System.Threading.Tasks.Task(Of String) Implements SH_WS_Produccion.SH_WSSoap.GET_Lecturas_FechaAsync
            Return MyBase.Channel.GET_Lecturas_FechaAsync(NombreDispositivo, Fecha)
        End Function
        
        Public Function GET_Servidor_Fecha() As String Implements SH_WS_Produccion.SH_WSSoap.GET_Servidor_Fecha
            Return MyBase.Channel.GET_Servidor_Fecha
        End Function
        
        Public Function GET_Servidor_FechaAsync() As System.Threading.Tasks.Task(Of String) Implements SH_WS_Produccion.SH_WSSoap.GET_Servidor_FechaAsync
            Return MyBase.Channel.GET_Servidor_FechaAsync
        End Function
        
        Public Function GET_Dispositivos_Configuración(ByVal NombreDispositivo As String) As String Implements SH_WS_Produccion.SH_WSSoap.GET_Dispositivos_Configuración
            Return MyBase.Channel.GET_Dispositivos_Configuración(NombreDispositivo)
        End Function
        
        Public Function GET_Dispositivos_ConfiguraciónAsync(ByVal NombreDispositivo As String) As System.Threading.Tasks.Task(Of String) Implements SH_WS_Produccion.SH_WSSoap.GET_Dispositivos_ConfiguraciónAsync
            Return MyBase.Channel.GET_Dispositivos_ConfiguraciónAsync(NombreDispositivo)
        End Function
        
        Public Function NEW_Dispositivo(ByVal NOMBRE_DISP As String, ByVal IP As String, ByVal ROL As String, ByVal LOCALIZACION As String, ByVal MODELO As String) As Boolean Implements SH_WS_Produccion.SH_WSSoap.NEW_Dispositivo
            Return MyBase.Channel.NEW_Dispositivo(NOMBRE_DISP, IP, ROL, LOCALIZACION, MODELO)
        End Function
        
        Public Function NEW_DispositivoAsync(ByVal NOMBRE_DISP As String, ByVal IP As String, ByVal ROL As String, ByVal LOCALIZACION As String, ByVal MODELO As String) As System.Threading.Tasks.Task(Of Boolean) Implements SH_WS_Produccion.SH_WSSoap.NEW_DispositivoAsync
            Return MyBase.Channel.NEW_DispositivoAsync(NOMBRE_DISP, IP, ROL, LOCALIZACION, MODELO)
        End Function
    End Class
End Namespace
